### PR TITLE
Add folders to project

### PR DESCRIPTION
**Pull request by eirikura**
# What?

Added folders so the project resembles the folder structures from class.
# Why?

This is a routine folder structure for java applications.
# Reviewer checklist

[X] - The change introduces no untested code
[X] - The change passes all existing tests
[X] - The change introduces no typos or formatting errors

### CODE REVIEW

**Comment by eirikura** [comment]
Aðeins að þjófstarta :)

**Comment by Sturla** [comment]
LGTM

**Comment by solvip** [comment]
I wonder if the path should be com/github/hundarogborn/tictactoe ?

**Comment by solvip** [comment]
LGTM!

**Pull request merged**
