### PR TITLE
Buildscripts

### PR DESCRIPTION
**Pull request by diddibjoss**
# What?

Adding buildscripts

### CODE REVIEW

**Comment by solvip** [comment]
To get the build to go green, do:

```
git checkout master
git pull
git checkout buildscripts
git merge master
git push
```

Otherwise, LGTM!  :ship: :it:

**Comment by solvip** [comment]
gradlew is probably not executable:

```
chmod +x gradlew
git add gradlew
...
```

**Comment by solvip** [comment]
LGTM :ship: :it:

**Comment by eirikura** [comment]
LGTM

**Comment by rebekka123** [comment]
LGTM

**Pull request merged**
