### PR TITLE
Remove plumbing for variable sized boards

### PR DESCRIPTION
**Pull request by solvip**
# What?

Stop supporting variable sized boards in board + engine constructors
# Why?

The rest of the game doesn't support anything but 3x3.  We can implement this again if and when we do that.
# Reviewer checklist

[ ] - The change introduces no untested code
[ ] - The change passes all existing tests
[ ] - The change introduces no typos or formatting errors

### CODE REVIEW

**Comment by rebekka123** [comment]
LGTM 💯

**Review by diddibjoss — APPROVED** [review]
Flott einfaldara

**Review by sveinng — APPROVED** [review]
I hope you stashed the code though!

**Review by eirikura — APPROVED** [review]
Little bit better like this 👍

**Comment by solvip** [comment]
@sveinng no stash - you can find it in the git history :)

**Pull request merged**
