### PR TITLE
Design report

### PR DESCRIPTION
**Pull request by solvip**
# What?

Add a design report, roughly describing the high-level architecture of our application
# Why?

It's a requirement of the assignment
# Reviewer checklist

[ ] - The change introduces no untested code
[ ] - The change passes all existing tests
[ ] - The change introduces no typos or formatting errors

### CODE REVIEW

**Review by eirikura — APPROVED** [review]
Looking good :)

**Comment by rebekka123** [comment]
LGTM 💯

**Comment by sveinng** [comment]
Good stuff!

**Review by diddibjoss — APPROVED** [review]

**Comment by Sturla** [comment]
LGTM

**Pull request merged**
